video/urls.py
from django.urls import path

from video import views


app_name = "video"
urlpatterns = [
    path('video/', views.upload, name='upload'),
    # ex: video/1/
    path('video/<category>/<tag>', views.video, name='video'),
    # ex: delete/1/
    path('delete/<category>/<tag>', views.deletevideo, name='delete'),
    # ex: poster/1/
    path('poster/<category>/<tag>/', views.poster, name='poster'),
]

video/templates/video/addvideo.html
{% extends "baselayout.html" %}

{% block script %}

{% endblock %}

{% block content %}


<form action="/video/upload/" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{form}}
<input type='submit' value='submit'/>
</form>


{% if video %}

<p>File: {{video.videofile.url}}</p>

<video src="{{video.videofile.url}}"/>

{% endif %}



{% if error %}
<p>Error: {{error}}</p>
{% endif %}

{% endblock %}

video/templates/video/javascript.html
  {% load static %}

  <!-- JS required for video display -->
    <script src="//vjs.zencdn.net/6.2.0/video.js"></script>
    <script type="text/javascript" src="{% static 'js/videojs-looper.js' %}"></script>
    <script>
        $('.thumbnail-video-modal').on('shown.bs.modal', function(event) {
            id = $(event.target).find('.video-js').attr('id');
            videojs(id).play();
        })
    </script>
    <!-- end video JS -->

video/templates/video/player.html
<div class='video-wrapper'>
{% if video %}
    <video id='signbank-video{{id|slugify}}' class="video-js vjs-default-skin"
      {% if width > 150 %}controls{% endif %} {# no room for controls on small videos #}
      preload="auto" autoplay muted width="{{width}}" height="{{height}}"
      poster="{{video.poster_url}}"
      data-setup='{
          "playbackRates": [0.25, 0.5, 1.0, 1.5],
          "plugins": {"looper": true},
          "controlBar": { "volumeMenuButton": false }
    }'  >
     <source src="{{video.get_absolute_url}}" type="video/mp4" />
    </video>
{% else %}
<p>No Video</p>
{% endif %}
</div>

video/templates/video/success_page.html
{% extends "baselayout.html" %}

{% block script %}
{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

video/templates/video/thumbnail-popup.html
{% if video %}
<!-- Link to trigger modal -->
<div class="video-thumbnail">
    <a href="#"  data-toggle="modal" data-target="#{{id}}">
            <img src="{{video.poster_url}}" width=150px alt="Sign Video thumbnail">
    </a>
</div>

<!-- Modal -->
<div class="modal fade thumbnail-video-modal" id="{{id}}" tabindex="-1" role="dialog" aria-labelledby="{{id}}Label">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
            <video id="{{id}}player" class="video-js vjs-default-skin"
            style="margin: auto"
                controls
                preload="{{preload}}" muted  width="{{width}}" height="{{height}}"
                poster="{{video.poster_url}}"
                data-setup='{
                    "playbackRates": [0.25, 0.5, 1.0, 1.5],
                    "plugins": {"looper": true},
                    "fluid" : true,
                    "controlBar": { "volumeMenuButton": false }
              }'  >
               <source src="{{video.get_absolute_url}}" type="video/mp4" />

               <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
            </video>
           </div>
        </div>
    </div>
</div>

{% else %}
<p>No Video</p>
{% endif %}

video/templates/video/upload_modal.html
<!-- http://bootsnipp.com/snippets/featured/bootstrap-drag-and-drop-upload -->
{% load bootstrap3 %}

<div class="modal fade" id="{{id}}" tabindex="-1"
     role="dialog" aria-labelledby="#uploadModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-sm">
       <div class="modal-content">
           <div class='modal-header'>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
               <h2 id='uploadModalTitle'>Upload a Video</h2>
           </div>
           <form action="{% url 'video:upload' %}" method="post" enctype="multipart/form-data" id="video_upload_form">

               <div class='modal-body'>

                    <h4>Select files from your computer</h4>
                    {% csrf_token %}
                    <div class="form-inline">
                      <div class="form-group">
                          {% bootstrap_form form layout="inline" %}
                      </div>
                    </div>
               </div>
               <div class="modal-footer">
                   <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                   <button type="submit" class="btn btn-sm btn-primary" id="js-upload-submit">Upload</button>
                </div>
            </form>
       </div>
   </div>
</div>

video/templates/video/uploadform.html
<form action="{% url 'video:upload' %}" method="post" enctype="multipart/form-data" id="video_upload_form">
  {% csrf_token %}
  {{form}}
  <input class='btn btn-primary' type='submit' value='{% if form.fields.videofile.widget.attrs.multiple %}Upload Videos{% else %}Upload Video{% endif %}'/>
</form>